/*----------------------------------------------------------
 *				HTBLA-Leonding
 * ---------------------------------------------------------
 * Exercise Number: n/a
 * Title:			Configuration Options
 * Author:			S. Schraml
 * ----------------------------------------------------------
 * Description:
 * Global application configuration options
 * ----------------------------------------------------------
 */
#ifndef ___CONFIGURATION_H
#define ___CONFIGURATION_H

/** 
 * Selects the implementation based on list.h. 
 * To use an array instead, comment this define. 
 */
#define LIST_VARIANT 1

/** The number of additional items when the list capacity need to be incremented. */
#define CAPACITY_INCREMENT 64

/** The largest value that is generated by the randomizer */
#define MAX_VALUE 1024 * 1024

#endif
